## Coalescent theory practical work through - Daniel Wegmann

# Q1) Given a constant population of size 2N = 100, 
# what is the probability that two individuals pick the same parent one generation before? 
# What that they pick the same parent two generations before?

# the probability that two individuals pick the same parent one generation before 
# is P(t2 = 1) = 1/(2N) = 1/100 = 0.01.

# the probability that two individuals pick the same parent two generations before
# is P(t2 = 2) = (1 - 1/(2N)) * (1/(2N)) = (1 - 1/100) * (1/100) = (99/100) * (1/100) = 0.0099.

# Q2) A researcher sequences a DNA fragment of length 10kb of a diploid individual 
# and detects 21 heterozygous sites. Assume that μ (mutation rate) = 10−9 per site for this segment 
# and that the assumptions of the standard coalescent and the infinites sites model hold.

# a) what is the effective population size? 

# under the infite sites model, E[π] = 4Neμ. Where pi is the average number of 
# pairwise differences between two sequences.
# therefore to estimate effective population size Ne = π/(4μ).
# Here, π = 21/10000 = 0.0021 and μ = 10^-9, therefore Ne = 0.0021/(4*10^-9) = 525000.
# The 21 is the number of heterozygous sites, and the 10kb is the length of the DNA fragment.
# So an estimate of Ne is 525,000.

# b) what is the expected time to the most recent common ancestor (TMRCA) of the two sequences?

# under the standard coalescent, E[TMRCA] = 2Ne generations.
# therefore, E[TMRCA] = 2 * 525000 = 1050000 generations.

# Q3) Consider a sample of two diploid individuals from a population for which 
# the assumptions of the standard coalescence model holds true. 
# What is the probability that the two sequences of the first individual
# are more closely related to each other than they are to any of the sequences of the
# other individual? 

# Case 1
# the probability that the two lineages from the first individual are the
# first to coalesce happens with the probability = 1/6
# this is explained by the fact that there are 3 lineages in total (2 from the first individual 
# and 1 from the second individual

# Case 2
# if the lineages of the other individual coalesce first, 
# the probability that the lineages of the other coalesce first is
# also 1/6

# therefore the probability of the second coalescence event between the lineages of the first individual
# is 1/3 

# the total probability of case 2 is 1/6 * 1/3 = 1/18

#Hence, the total probability that the lineages of the first individual
#are more closely related than any of them is to a sequence of another individual
# is 1/6 + 1/18 = 4/18 = 2/9 = 0.2222

# Q4) The following DNA sequences were obtained from a population:
# ind 1 ATCGTGCACA ACTTGCAACA
# ind 2 ATCGTGGACC ACTTGCAACT
# ind 3 AGCGTGGACC ACTTGCAACT

# Calculate the Tajima estimator θT per site from this data.
# pairwise differences between the sequences where individuals are either i or j 
# (dij) are:
# d12 = 3
# d13 = 4
# d23 = 1

# the average number of pairwise differences between the sequences is
# π = (d12 + d13 + d23)/3 = (3 + 4 + 1)/3 = 8/3 = 2.6667
# hence the Tajima estimator θT per site is θT = π/L = 2.6667/20 = 0.1333 per base pair

# Building trees generated by fastcoal

# first have a plotTrees function:

plotTrees <- function(trees, popCol=c("black", "orange2", "purple")){
  maxHeight <- max(unlist(lapply(trees, function(x){ max(branching.times(x)) })))
  nCols <- ceiling(sqrt(length(trees)))
  nRows <- ceiling(length(trees) / nCols)
  par(mfrow = c(nRows, nCols), oma=c(0,4,0,0), las=1, xpd=NA)
  
  for(tr in 1:length(trees)){
    plotTree(trees[[tr]], direction="downwards", ylim=c(0, maxHeight),
             lwd=0.6, ftype="off", mar=c(0.1,0.7,0.1,0.7))
    
    if(tr %% nCols == 1){ axis(side = 2)}
    
    #add tips and color by population
    pop <- as.numeric(unlist(lapply(strsplit(trees[[1]]$tip.label, "[.]"), '[', 2) ))
    
    nTips <- length(trees[[tr]]$tip.label);
    symbols(1:nTips, rep(0, nTips), circles=rep(0.4, nTips), add=TRUE, inches=0.03, fg=NA, bg=popCol[pop])
  }
}

library(phytools)
trees <- read.nexus("constsize_1_true_trees.trees")
plotTrees(trees)

# now we plot the average tree height
mean(unlist(lapply(trees, function(x){ max(branching.times(x)) })))

# answer = 16110.22

library(phytools)
trees <- read.nexus("constsize_1_mut_trees.trees")
plotTrees(trees)

# again we plot the average tree height
mean(unlist(lapply(trees, function(x){ max(branching.times(x)) })))

# answer = 15.3

# with mutation, the average tree height is much smaller than without mutation. 
# This is because with mutation, the coalescent events are more recent, 
# leading to shorter branch lengths and thus a smaller average tree height.
# Coalescent events are more recent because mutations introduce new lineages, 
# Therefore, the time to the most recent common ancestor is shorter, resulting in a smaller average tree height.
# The theory behind this is that the coalescent process is affected by the mutation rate.

# Q5) Use the above setup to simulate and compare trees under constant size populations of different sizes. 
# Always compute the average tree height using

mean(unlist(lapply(trees, function(x){ max(branching.times(x)) })))

# the above was a population size of 10000
# without mutation, the average tree height is 16110.22
# with mutation, the average tree height is 15.3

# now for a constant population of 1000 with no mutation 
trees <- read.nexus("constsize1000_1_true_trees.trees")
plotTrees(trees)
mean(unlist(lapply(trees, function(x){ max(branching.times(x)) })))
# average tree height = 2080

# now for a constant population of 1000 with mutation
trees <- read.nexus("constsize1000_1_mut_trees.trees")
plotTrees(trees)
mean(unlist(lapply(trees, function(x){ max(branching.times(x)) })))
# average tree height with mutation = 1.7

# now for a constant population of 100 with no mutation
trees <- read.nexus("constsize100_1_true_trees.trees")
plotTrees(trees)
mean(unlist(lapply(trees, function(x){ max(branching.times(x)) })))
# average tree height = 180

# now for a constant population of 100 with mutation
trees <- read.nexus("constsize100_1_mut_trees.trees")
plotTrees(trees)
mean(unlist(lapply(trees, function(x){ max(branching.times(x)) })))
# average tree height with mutation = 0.2

# Overall results:
# Without mutation:
# pop size 10000 = 16110.22
# pop size 1000 = 2080
# pop size 100 = 180
# this is explained by the fact that the average tree height is 
# proportional to the effective population size.

# With mutation:
# pop size 10000 = 15.3
# pop size 1000 = 1.7
# pop size 100 = 0.2
# this is explained by the fact that the average tree height is
# proportional to the effective population size and the mutation rate.
